config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  devise_for :users, controllers: { registrations: "users/registrations" }
  root 'tasks#index'
  get '/dashboard', to: 'tasks#index'
  get '/complete/:id', to: 'tasks#complete', as: 'complete'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true

  scope :completed, -> { where(completed: true) }

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def mark_complete!
    self.update_attribute(:completed, true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy

  def soft_user?
    self.email.empty?
  end

  def needs_engagement?
      tasks = Task.where(soft_token: self.soft_token)
      if self.soft_user? && tasks.count >= 2
        true
      end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!(*args)
    current_user.present? || super(*args)
  end

  def current_user
    super || User.where(soft_token: soft_token).first_or_initialize
  end

  private

  def soft_token
    session[:user_token] ||= SecureRandom.hex(8)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy]

  respond_to :html
  respond_to :js

  def index
    @user = current_user
    if @user.soft_user?
      @tasks = Task.where(soft_token: @user.soft_token)
    else
      @tasks = @user.tasks.all
    end
    respond_with(@tasks)
  end

  def new
    @task = Task.new
    respond_with(@task)
  end

  def edit
  end

  def create
    @user = current_user
    @task = Task.new(task_params)

    if @user.soft_user?
      @task.soft_token = @user.soft_token
    end

    @task.save
    respond_with(@task)

  end

  def update
    @task.update(task_params)
    respond_with(@task)
  end

  def destroy
    @task.destroy
    respond_with(@task)
  end

    def complete
      @task = Task.find(params[:id])
      @task.mark_complete!
    end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :completed, :user_id)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def merge_tasks
    tasks = Task.where(soft_token: current_user.soft_token)
    tasks.map do |task|
      task.user = current_user
      task.user_id = current_user.id
      task.save!
    end
  end

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
     devise_parameter_sanitizer.for(:sign_up) << :soft_token
  end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    merge_tasks
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_analytics.html.erb
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-59099331-3', 'auto');
ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>TaskSnail | AJAX Task Management App</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="row">
      <div class="small-10 medium-4 large-6 large-centered medium-centered small-centered columns"><div class="logo"><%= image_tag("tasksnail.svg", width: 300) %></div>
      </div>

    <div class="row">
      <div class="small-10 medium-8 large-8 large-centered medium-centered small-centered columns"><%= yield %></div>
    </div>

    <%= render "layouts/analytics" %>

  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task, remote: true) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, label: false, placeholder: "Task Name" %>
  </div>

  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<li>
  <%= div_for task do %>
<div class="panel">
<h3><%= task.name %></h3>
<ul>
  <li><%= link_to "Edit Task", edit_task_path(task), remote: true %></li>
  <li><%= link_to "Mark Complete", complete_path(task), remote: true %></li>
  <li><%= link_to "Delete Task", task, remote: true, method: :delete %></li>
</ul>
<% end %>
</div>
</li>

app/views/tasks/complete.js.erb
$('div#<%= dom_id(@task) %>').fadeOut();
$('.completed-tasks ul:first').append('<%= j render partial: "task", locals: {task: @task} %>');
$('div#<%= dom_id(@task) %>').find('h3').css('text-decoration', 'line-through');

app/views/tasks/create.js.erb
<% if current_user.needs_engagement? %>

$('.my-tasks ul:first').append('<%= j render partial: "task", locals: {task: @task} %>');
$('.new-task-button').replaceWith('<h4>Registration Required to Add More Tasks!</h4>');
$('form').hide();

<% else %>

$('.my-tasks ul:first').append('<%= j render partial: "task", locals: {task: @task} %>');
$('.new-task-button').show();
$('form').hide();

<% end %>

app/views/tasks/destroy.js.erb
$('div#<%= dom_id(@task) %>').fadeOut();

app/views/tasks/edit.js.erb
$('form').hide();
$('div#<%= dom_id(@task) %>').find('.panel').append('<%= j render("form") %>');

app/views/tasks/index.html.erb
<h3>Welcome</h3>

<p>Welcome to TaskSnail, an AJAXified Rails App by CodeDiode.io</p>

<p>Learn how to build this app from scratch in 3 lessons</p>

<ul>
  <li><%= link_to "Devise Gradual Engagement", "http://codediode.io/lessons/364-gradual-engagement-with-rails-and-devise" %></li>
  <li><%= link_to "AJAXify a Rails App", "http://codediode.io/lessons/1904-ajaxified-one-page-application-with-rails" %></li>
  <li><%= link_to "Frontend Magic with Zurb Foundation & Rails", "http://codediode.io/lessons/8027-zurb-foundation-rails" %></li>
</ul>

<% if @user.soft_user? %>

<h3>Completed Tasks</h3>
<div class='completed-tasks'>
  <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
  <% @tasks.completed.each do |task| %>
  <%= render task %>
  <% end %>
  </ul>
</div>

<hr />

<h3>Incomplete Tasks</h3>
<div class="my-tasks">
  <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
  <% @tasks.where(completed: nil).each do |task| %>
  <%= render task %>
  <% end %>
  </ul>
</div>

<% unless current_user.needs_engagement? %>
<div class="new-task-form"></div>
<%= link_to "New Task", new_task_path, remote: true, class: "new-task-button button radius" %>

<% else %>

<h4>Registration Required to Add More Tasks!</h4>

<% end %>

<% else %>

<h3>Completed Tasks</h3>
<div class='completed-tasks'>
  <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
  <% @tasks.where(completed: true).each do |task| %>
  <%= render task %>
  <% end %>
</ul>
</div>

<hr />

<h3>Incomplete Tasks</h3>
<div class="my-tasks">
  <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
  <% @tasks.where(completed: nil).each do |task| %>
  <%= render task %>
  <% end %>
  </ul>
</div>

<div class="new-task-form"></div>
<%= link_to "New Task", new_task_path, remote: true, class: "new-task-button button radius" %>
<% end %>

<% if current_user.soft_user? %>
<p><%= link_to "Sign Up", new_user_registration_path %> or <%= link_to "Login", new_user_session_path %></p>
<% else %>

<p><%= link_to "Edit Profile", edit_user_registration_path %> or <%= link_to "Logout", destroy_user_session_path, method: :delete %></p>

<% end %>

app/views/tasks/new.js.erb
$('.new-task-button').after('<%= j render("form") %>');
$('.new-task-button').hide();

app/views/tasks/update.js.erb
$('div#<%= dom_id(@task) %>:first').replaceWith('<%= j render partial: "task", locals: {task: @task} %>');